name: Build Windows via upstream CI

on:
  workflow_dispatch:

jobs:
  call-upstream:
    name: Upstream Flutter build
    # Вызов их reusable-workflow. Убедись, что файл существует у апстрима:
    # rustdesk/rustdesk/.github/workflows/flutter-build.yml
    uses: rustdesk/rustdesk/.github/workflows/flutter-build.yml@master

    # Параметры, которые поддерживает их workflow (оставляем типичные):
    with:
      upload-artifact: true    # чтобы exe пришёл артефактом к этому ранe
      upload-tag: false

    # Передаём разрешения/секреты текущего репозитория (обычно не требуются, но безопасно)
    secrets: inherit
